### ISSUE TITLE
https://min.io/ initial attempt

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/gp-miniio-website#1]
The purpose of this issue is that the team leader (@svf97 ) would try to create the setup for https://min.io/ using instruction from

https://github.com/k8-proxy/k8-reverse-proxy/tree/develop/stable-src:

And also while considering feedback from:
https://github.com/k8-proxy/gp-engineering-website

The deliverables of this task are:
Up and running proxy setup as per the instructions.
Report back discovered bugs or issues to the original repo (https://github.com/k8-proxy/k8-reverse-proxy).

**Comment by svf97** [comment]
Hello @mahnouman , please find my issue [here](https://github.com/k8-proxy/k8-reverse-proxy/issues/65)

**Comment by dtollaku** [comment]
This is not needed anymore
